### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by AbelHo** [AbelHo/DolphinSpeaker.jl#1]
- [ ] startup warnings removal
- [ ] update FLAC.jl when pull request is accepted
- [ ] improve tdoa alogorithm
- [ ] easy function to generate individual detection plot
- [ ] plot sync signal detection n save plot for verification
- [ ] plot out of video fov signal detections
- [ ] add auto analyse and plot detected events VS time for each file, produce CSV
- [ ] UNIT TESTING
- [ ] detection times in video chart
